-- ============================================================
--  Lab 5 — Database Setup Script
--  Run this in phpMyAdmin > SQL tab before testing either app
-- ============================================================

-- -----------------------------------------------
-- 1. VULNERABLE APP database (plain-text passwords)
-- -----------------------------------------------
CREATE DATABASE IF NOT EXISTS lab5;
USE lab5;

CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(50),
    password VARCHAR(50)
);

-- Clear any existing data and re-insert clean test records
DELETE FROM users;
INSERT INTO users VALUES ('user1',  'pass1');
INSERT INTO users VALUES ('admin',  'admin123');

-- -----------------------------------------------
-- 2. SECURE APP database (bcrypt-hashed passwords)
--    Run generate_hashes.php first to get hashed values,
--    then paste them below, OR use the auto-setup script.
-- -----------------------------------------------
CREATE DATABASE IF NOT EXISTS lab5_secure;
USE lab5_secure;

CREATE TABLE IF NOT EXISTS users (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50)  NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL          -- bcrypt hash is ~60 chars; 255 is safe
);

DELETE FROM users;
-- Hashes are generated by generate_hashes.php
-- Paste the output of that script here, for example:
-- INSERT INTO users (username, password) VALUES ('user1',  '$2y$12$...');
-- INSERT INTO users (username, password) VALUES ('admin',  '$2y$12$...');

-- See README.md > "Setting Up the Secure App Database" for full instructions.
